name: CI/CD Pipeline

on:
  # Trigger on pull requests
  pull_request:
    branches:
      - main

  # Trigger on pushes to the main branch
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup .NET
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Build the project
      - name: Build the project
        run: dotnet build --configuration Release

      # Run tests
      - name: Run unit tests
        run: dotnet test

  deploy:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/main')
    needs: build-and-test  # Ensure build and test job completes successfully
    runs-on: ubuntu-latest

    steps:
      - name: checkoutRepo
        uses: actions/checkout@v2  

      - name: Build and Deploy
        uses: ./.github/actions
        with:
          aws-role: ${{ secrets.AWS_SAM_DEPLOYMENT_ROLE }}
          aws-region: 'eu-west-2'
          dotnet-version: '8.x'
          template-file-path: ./src/NotifyService.Api/serveless.template
          stack-name: daotest
          s3-bucket-name: daonotifyservice
      