name: CI/CD Pipeline

on:
  # Trigger on pull requests
  pull_request:
    branches:
      - main

  # Trigger on pushes to the main branch
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup .NET
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Build the project
      - name: Build the project
        run: dotnet build --configuration Release

      # Run tests
      - name: Run unit tests
        run: dotnet test

  deploy:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/main')
    needs: build-and-test  # Ensure build and test job completes successfully
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Lambda tools
      - name: Install Amazon Lambda Tools
        run:  dotnet tool install -g Amazon.Lambda.Tools

      # Deploy to AWS Lambda
      - name: Deploy to AWS Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-west-2
        working-directory: ./src/NotifyService.Api
        run: dotnet lambda deploy-serverless --template ./serverless.yml --stack-name NotifyService --region $AWS_REGION
