name: NotifyService

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main
        
env:
  DOTNET_VERSION: '8.x'
  AWS_REGION: 'eu-west-2'
  PATH_TO_TEMPLATE_FILE: './src/NotifyService.Api/serverless.template'
  STACK_NAME: 'NotifyService'
  S3_BUCKET: 'Backend'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release

      - name: Run unit tests
        run: dotnet test

  deploy:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/main')
    needs: build-and-test
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - run: sam build -t ${{ env.PATH_TO_TEMPLATE_FILE }} --parameter-overrides LambdaArchitecture=x86_64
        shell: bash
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name ${{ env.STACK_NAME }} --s3-prefix ${{ env.STACK_NAME }} --s3-bucket ${{ env.S3_BUCKET }} --capabilities CAPABILITY_IAM --parameter-overrides LambdaArchitecture=x86_64
        shell: bash